# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pace < Formula
  desc "A CLI tool for task management, notes, focus timer, and more"
  homepage "https://github.com/lucas-tremaroli/pace"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.3.0/pace_1.3.0_Darwin_x86_64.tar.gz"
      sha256 "447874a3ac6945ce3cd6cfe30d54669775d550adae3276d9e90e7f3cb98233bc"

      def install
        bin.install "pace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.3.0/pace_1.3.0_Darwin_arm64.tar.gz"
      sha256 "f9881872f6360e1e0f06096441422fab792cd996aeeba6cf47645b0d5f28ac96"

      def install
        bin.install "pace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.3.0/pace_1.3.0_Linux_x86_64.tar.gz"
      sha256 "e584315eb20473a63d0d9af8d382661267719f83f147c26d4c6402c81375729d"
      def install
        bin.install "pace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.3.0/pace_1.3.0_Linux_arm64.tar.gz"
      sha256 "28923506be0272ad0b61f5df2be0d6558628c82b10dc69a33a3657191a4bde16"
      def install
        bin.install "pace"
      end
    end
  end
end
