# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pace < Formula
  desc "A CLI tool for task management, notes, focus timer, and more"
  homepage "https://github.com/lucas-tremaroli/pace"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.0.0/pace_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "19383e84c8bbd8c916e4b0fcf73f121e3f9364479976c28921d825211b39d864"

      def install
        bin.install "pace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.0.0/pace_1.0.0_Darwin_arm64.tar.gz"
      sha256 "be64ec78065f270879b33fe92d81e3c8cec4c755a4a1ecd1cf5cf5f67f45cb25"

      def install
        bin.install "pace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.0.0/pace_1.0.0_Linux_x86_64.tar.gz"
      sha256 "ef3fa517219ac83fc8c38936433184581c48bfbacfd64cb3281d59ad9cbfa110"
      def install
        bin.install "pace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.0.0/pace_1.0.0_Linux_arm64.tar.gz"
      sha256 "9f677f2750ebe162a4da518b731b69596ef060ef5fed00f36517697082ce9264"
      def install
        bin.install "pace"
      end
    end
  end
end
