# This file was generated by GoReleaser. DO NOT EDIT.
cask "pace" do
  name "pace"
  desc "A CLI tool for task management, notes, focus timer, and more"
  homepage "https://github.com/lucas-tremaroli/pace"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pace"

  on_macos do
    on_intel do
      url "https://github.com/lucas-tremaroli/pace/releases/download/v#{version}/pace_#{version}_Darwin_x86_64.tar.gz"
      sha256 "ec6fa4d11cbea991b4cafef93ca168311509843938ad08135d3e3cd580cae7aa"
    end
    on_arm do
      url "https://github.com/lucas-tremaroli/pace/releases/download/v#{version}/pace_#{version}_Darwin_arm64.tar.gz"
      sha256 "0de837f2535544c60d96862e5b85e143ac8e1d0017a2e0fc85a3430e02c752f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lucas-tremaroli/pace/releases/download/v#{version}/pace_#{version}_Linux_x86_64.tar.gz"
      sha256 "03442e5b8f5812a037c8e26f6b8aed02ba1e3adea09718ccc57682a8721cee5e"
    end
    on_arm do
      url "https://github.com/lucas-tremaroli/pace/releases/download/v#{version}/pace_#{version}_Linux_arm64.tar.gz"
      sha256 "de10fa35c354319f30fb26900dfb478f24617b8287983a52090c7ba96c2ec7f6"
    end
  end

  # No zap stanza required
end
