# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pace < Formula
  desc "A CLI tool for task management, notes, focus timer, and more"
  homepage "https://github.com/lucas-tremaroli/pace"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.0.0/pace_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "46810bd1fee938605efaf630ba55981e13ebaafa5d54a031da42a8f3d865afca"

      def install
        bin.install "pace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.0.0/pace_1.0.0_Darwin_arm64.tar.gz"
      sha256 "4a9574a55a63d92cf7465ed3930cbabb3cdf2283a5335ccff025a199114ee4ac"

      def install
        bin.install "pace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.0.0/pace_1.0.0_Linux_x86_64.tar.gz"
      sha256 "7cb6c369fdf8b476ffa063e8983d77c3720be6201983d4bffd400f818e501757"
      def install
        bin.install "pace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucas-tremaroli/pace/releases/download/v1.0.0/pace_1.0.0_Linux_arm64.tar.gz"
      sha256 "4ea2a38bd9393439869b6f573bde8abff6078f5ba9734893ff6b1031299aa243"
      def install
        bin.install "pace"
      end
    end
  end

  test do
    system "#{bin}/pace", "--help"
  end
end
